# PyTorch Fundamentals

## Creating tensors

In [1]:
import torch
torch.__version__

'2.2.2'

In [2]:
scalar = torch.tensor(8)
scalar

tensor(8)

In [3]:
scalar.item()

8

In [4]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([3])

In [7]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
matrix.ndim

2

In [12]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                        
                        [[7, 8, 9],
                         [0, 1, 2]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [0, 1, 2]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([2, 2, 3])

In [22]:
random_tensor = torch.rand(size=(3, 4, 2))
random_tensor, random_tensor.dtype

(tensor([[[0.3619, 0.5937],
          [0.7660, 0.9577],
          [0.7303, 0.4897],
          [0.1677, 0.3162]],
 
         [[0.1423, 0.1616],
          [0.9565, 0.8836],
          [0.2337, 0.8261],
          [0.3025, 0.3215]],
 
         [[0.4580, 0.0206],
          [0.1013, 0.9163],
          [0.2637, 0.7222],
          [0.5262, 0.8032]]]),
 torch.float32)

In [31]:
random_image_tensor = torch.rand(size=(244, 244, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [34]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 4.0, 6.0],
                               dtype=None,  # Default is None, which is float32 or whatever type is passed
                               device=None, # Default is None, which is cpu,
                               requires_grad=False) # If True, operations are saved in memory
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [55]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Operation between tensors

In [69]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
tensor + 10

tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [70]:
tensor - 10

tensor([[-9, -8, -7],
        [-6, -5, -4],
        [-3, -2, -1]])

In [71]:
tensor * 10

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [72]:
tensor / 10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])

In [73]:
tensor * tensor

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [74]:
tensor @ tensor

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [75]:
torch.matmul(tensor, tensor)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [77]:
tensor.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

## Aggregation

In [80]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
x.max()

tensor(90)

In [87]:
x.min()

tensor(0)

In [86]:
x.type(torch.float).mean()

tensor(45.)

In [89]:
x.type(torch.float).median()

tensor(40.)

In [90]:
x.sum()

tensor(450)

In [91]:
x.argmax()

tensor(9)

In [92]:
x.argmin()

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing

In [101]:
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [107]:
x.reshape(2, 4)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [110]:
x.view(2, 4)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [98]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [111]:
torch.stack([x, x, x, x, x])

tensor([[1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.]])

In [113]:
x_reshaped = x.reshape(1, 8)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])

In [114]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [116]:
x.unsqueeze(0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])

In [117]:
x.numpy()

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

## Reproducibility

In [125]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [128]:
tensor_in_gpu = torch.tensor([1, 2, 3,], dtype=torch.float, device="cuda")
tensor_in_gpu

tensor([1., 2., 3.], device='cuda:0')

In [129]:
# Can't transform it to NumPy if on GPU
tensor_in_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [130]:
tensor_in_gpu.cpu().numpy()

array([1., 2., 3.], dtype=float32)