# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.5304, 0.4369, 0.3358, 0.9638, 0.5432, 0.5457, 0.7724],
        [0.5690, 0.2578, 0.6018, 0.3780, 0.5919, 0.5026, 0.3928],
        [0.6372, 0.0211, 0.6932, 0.8996, 0.9586, 0.8965, 0.2981],
        [0.1336, 0.2975, 0.3781, 0.5538, 0.9456, 0.9885, 0.4980],
        [0.3932, 0.8551, 0.1122, 0.8282, 0.5236, 0.6922, 0.9583],
        [0.7910, 0.2188, 0.3191, 0.9806, 0.8395, 0.3439, 0.6448],
        [0.5614, 0.3022, 0.4274, 0.2387, 0.8712, 0.7083, 0.7453]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication 
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[2.3531],
        [2.1038],
        [2.6598],
        [2.4680],
        [2.5911],
        [2.3652],
        [2.6282]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
x = torch.rand(7, 7)
y = torch.rand(1, 7)

# Matrix multiply tensors
result = x @ y.T
result, result.size()

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())

# Create two random tensors on GPU
x = torch.rand(2, 3).cuda()
y = torch.rand(2, 3).cuda()
x, y

True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
result = x @ y.T
result, result.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(f"Maximum: {result.max()}")
# Find min
print(f"Minimum: {result.min()}")

Maximum: 0.5617256760597229
Minimum: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [27]:
# Find arg max
print(f"Maximum index: {result.argmax()}")

# Find arg min
print(f"Minimum index: {result.argmin()}")


Maximum index: 3
Minimum index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [30]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
tensor, tensor_squeezed


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))